config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "product#index"
  get '/product-detail/:product_name', to: 'product#productDetail', as: 'product_detail'

  get '/category/:category_name/products/', to: 'product#categoryProducts', as: 'category_products'

  # get '/login', to: 'users#user_login', as: 'login'
  # post "/login" => "users#check_credentials", as: :check_credentials
  # get "/logout" => "users#logout", as: :logout

  get '/about_us', to: 'home#about', as: 'about_us'
  get '/contact_us', to: 'home#contact', as: 'contact_us'

  get '/my-profile', to: 'users#profile', as: 'user_profile'
  get '/edit-profile', to: 'users#edit_profile', as: 'edit_profile'
  post '/update-profile/:id', to: 'users#update_profile', as: 'update_profile'


  get '/reset_password', to: 'users#new_password_reset', as: 'new_password_reset'
  post '/reset-password-action', to: 'users#create_password_reset', as: 'password_reset'
  get '/reset_password/:token/edit', to: 'users#edit_password_reset', as: :edit_password_reset
  patch '/reset_password/:token', to: 'users#update_password_reset', as: :reset_password


  get '/sign-up', to: 'users#sign_up_form', as: 'sign_up'
  post '/create-users', to: 'users#create_user', as: 'create_user'

  get '/cart', to: 'cart#index', as: 'my_cart'
  post '/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  get '/delete_cart/:id', to: 'cart#delete_cart', as: 'delete_cart'
  get '/checkout', to: 'cart#checkout', as: 'checkout'

  post '/place-an-order', to: 'order#place_order', as: 'place_an_order'

  namespace :admin do
    get '/', to: 'dashboard#login', as: 'login'
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    get 'users', to: 'dashboard#users', as: 'users'
    get 'orders', to: 'dashboard#orders', as: 'orders'
    get 'products', to: 'dashboard#products', as: 'products'
    get 'product/new', to: 'dashboard#new_product', as: 'add_product'
    post 'product/create', to: 'dashboard#create_product', as: 'create_product'
    get 'product/delete/:id', to: 'dashboard#delete_product', as: 'delete_product'
    get 'product/edit/:id', to: 'dashboard#edit_product', as: 'edit_product'
    get 'product/:id/remove-image', to: 'dashboard#remove_product_image', as: 'remove_product_image'
    patch 'product/update/:id', to: 'dashboard#update_product', as: 'update_product'

    resources :categories do
      member do
        get 'delete_category', to: 'categories#destroy_category', as: 'delete_category'
      end
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/admin/_header.html.erb
<header class="app-header fixed-top">
  <div class="app-header-inner">
    <div class="container-fluid py-2">
      <div class="app-header-content">
        <div class="row justify-content-between align-items-center">

          <div class="col-auto">
            <a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg>
            </a>
          </div><!--//col-->
          <div class="search-mobile-trigger d-sm-none col">
            <i class="search-mobile-trigger-icon fa-solid fa-magnifying-glass"></i>
          </div><!--//col-->
          <div class="app-search-box col">
            <form class="app-search-form">
              <input type="text" placeholder="Search..." name="search" class="form-control search-input">
              <button type="submit" class="btn search-btn btn-primary" value="Search"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>
          </div><!--//app-search-box-->

          <div class="app-utilities col-auto">
            <div class="app-utility-item app-notifications-dropdown dropdown">
              <a class="dropdown-toggle no-toggle-arrow" id="notifications-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" title="Notifications">
                <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bell icon" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2z"/>
                  <path fill-rule="evenodd" d="M8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
                </svg>
                <span class="icon-badge">3</span>
              </a><!--//dropdown-toggle-->

              <div class="dropdown-menu p-0" aria-labelledby="notifications-dropdown-toggle">
                <div class="dropdown-menu-header p-3">
                  <h5 class="dropdown-menu-title mb-0">Notifications</h5>
                </div><!--//dropdown-menu-title-->
                <div class="dropdown-menu-content">
                  <div class="item p-3">
                    <div class="row gx-2 justify-content-between align-items-center">
                      <div class="col-auto">
                        <img class="profile-image" src="assets/images/profiles/profile-1.png" alt="">
                      </div><!--//col-->
                      <div class="col">
                        <div class="info">
                          <div class="desc">Amy shared a file with you. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </div>
                          <div class="meta"> 2 hrs ago</div>
                        </div>
                      </div><!--//col-->
                    </div><!--//row-->
                    <a class="link-mask" href="notifications.html"></a>
                  </div><!--//item-->
                  <div class="item p-3">
                    <div class="row gx-2 justify-content-between align-items-center">
                      <div class="col-auto">
                        <div class="app-icon-holder">
                          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-receipt" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M1.92.506a.5.5 0 0 1 .434.14L3 1.293l.646-.647a.5.5 0 0 1 .708 0L5 1.293l.646-.647a.5.5 0 0 1 .708 0L7 1.293l.646-.647a.5.5 0 0 1 .708 0L9 1.293l.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .801.13l.5 1A.5.5 0 0 1 15 2v12a.5.5 0 0 1-.053.224l-.5 1a.5.5 0 0 1-.8.13L13 14.707l-.646.647a.5.5 0 0 1-.708 0L11 14.707l-.646.647a.5.5 0 0 1-.708 0L9 14.707l-.646.647a.5.5 0 0 1-.708 0L7 14.707l-.646.647a.5.5 0 0 1-.708 0L5 14.707l-.646.647a.5.5 0 0 1-.708 0L3 14.707l-.646.647a.5.5 0 0 1-.801-.13l-.5-1A.5.5 0 0 1 1 14V2a.5.5 0 0 1 .053-.224l.5-1a.5.5 0 0 1 .367-.27zm.217 1.338L2 2.118v11.764l.137.274.51-.51a.5.5 0 0 1 .707 0l.646.647.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.509.509.137-.274V2.118l-.137-.274-.51.51a.5.5 0 0 1-.707 0L12 1.707l-.646.647a.5.5 0 0 1-.708 0L10 1.707l-.646.647a.5.5 0 0 1-.708 0L8 1.707l-.646.647a.5.5 0 0 1-.708 0L6 1.707l-.646.647a.5.5 0 0 1-.708 0L4 1.707l-.646.647a.5.5 0 0 1-.708 0l-.509-.51z"/>
                            <path fill-rule="evenodd" d="M3 4.5a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm8-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5z"/>
                          </svg>
                        </div>
                      </div><!--//col-->
                      <div class="col">
                        <div class="info">
                          <div class="desc">You have a new invoice. Proin venenatis interdum est.</div>
                          <div class="meta"> 1 day ago</div>
                        </div>
                      </div><!--//col-->
                    </div><!--//row-->
                    <a class="link-mask" href="notifications.html"></a>
                  </div><!--//item-->
                  <div class="item p-3">
                    <div class="row gx-2 justify-content-between align-items-center">
                      <div class="col-auto">
                        <div class="app-icon-holder icon-holder-mono">
                          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bar-chart-line" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M11 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h1V7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7h1V2zm1 12h2V2h-2v12zm-3 0V7H7v7h2zm-5 0v-3H2v3h2z"/>
                          </svg>
                        </div>
                      </div><!--//col-->
                      <div class="col">
                        <div class="info">
                          <div class="desc">Your report is ready. Proin venenatis interdum est.</div>
                          <div class="meta"> 3 days ago</div>
                        </div>
                      </div><!--//col-->
                    </div><!--//row-->
                    <a class="link-mask" href="notifications.html"></a>
                  </div><!--//item-->
                  <div class="item p-3">
                    <div class="row gx-2 justify-content-between align-items-center">
                      <div class="col-auto">
                        <img class="profile-image" src="assets/images/profiles/profile-2.png" alt="">
                      </div><!--//col-->
                      <div class="col">
                        <div class="info">
                          <div class="desc">James sent you a new message.</div>
                          <div class="meta"> 7 days ago</div>
                        </div>
                      </div><!--//col-->
                    </div><!--//row-->
                    <a class="link-mask" href="notifications.html"></a>
                  </div><!--//item-->
                </div><!--//dropdown-menu-content-->

                <div class="dropdown-menu-footer p-2 text-center">
                  <a href="notifications.html">View all</a>
                </div>

              </div><!--//dropdown-menu-->
            </div><!--//app-utility-item-->

            <div class="app-utility-item app-user-dropdown dropdown">
              <a class="dropdown-toggle" id="user-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false"><%= image_tag("images/user.png", alt: "MyShop Logo") %></a>
              <ul class="dropdown-menu" aria-labelledby="user-dropdown-toggle">
                <li><a class="dropdown-item" href="account.html"><i class="fa fa-user"></i> Profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <%= button_to destroy_user_session_path, method: :delete, style: 'text-decoration:none;background: #fff;border: none;width:100%;' do %>
                  <li>
                    <span class="dropdown-item d-flex"><i class="fa fa-sign-out" style="margin-top: 4px;margin-right: 4px;"></i> Sign Out</span>
                  </li>
                <% end %>
              </ul>
            </div><!--//app-users-dropdown-->
          </div><!--//app-utilities-->
        </div><!--//row-->
      </div><!--//app-header-content-->
    </div><!--//container-fluid-->
  </div><!--//app-header-inner-->
  <div id="app-sidepanel" class="app-sidepanel">
    <div id="sidepanel-drop" class="sidepanel-drop"></div>
    <div class="sidepanel-inner d-flex flex-column">
      <a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
      <div class="app-branding">
        <a class="app-logo" href="<%= admin_dashboard_path %>"><%= image_tag("admin-logo.png", alt: "MyShop Logo", style: "width: 200px;") %></a>
      </div><!--//app-branding-->

      <nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
        <ul class="app-menu list-unstyled accordion" id="menu-accordion">
          <li class="nav-item">
            <a class="nav-link active" href="<%= admin_dashboard_path %>">
						        <span class="nav-icon">
						          <i class="fa fa-home" style="font-size: 22px;"></i>
						         </span>
              <span class="nav-link-text">Dashboard</span>
            </a>
          </li><!--//nav-item-->
          <li class="nav-item">
            <a class="nav-link" href="<%= admin_categories_path %>">
						        <span class="nav-icon">
                      <i class="fa fa-list-alt" style="font-size: 22px;"></i>
						         </span>
              <span class="nav-link-text">Categories</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= admin_products_path %>">
						        <span class="nav-icon">
                      <i class="fa fa-product-hunt" style="font-size: 22px;"></i>
						         </span>
              <span class="nav-link-text">Products</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= admin_orders_path %>">
						        <span class="nav-icon">
						        <i class="fa fa-shopping-bag" style="font-size: 22px;"></i>
						         </span>
              <span class="nav-link-text">Orders</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= admin_users_path %>">
						        <span class="nav-icon">
						        <i class="fa fa-users" style="font-size: 22px;"></i>
						         </span>
              <span class="nav-link-text">Users</span>
            </a>
          </li>
<!--          <li class="nav-item has-submenu">-->
<!--            <a class="nav-link submenu-toggle" href="#" data-bs-toggle="collapse" data-bs-target="#submenu-1" aria-expanded="false" aria-controls="submenu-1">-->
<!--              <span class="nav-icon">-->
<!--                <i class="fa fa-product-hunt" style="font-size: 22px;"></i>-->
<!--              </span>-->
<!--              <span class="nav-link-text">Pages</span>-->
<!--              <span class="submenu-arrow">-->
<!--                 <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">-->
<!--                    <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>-->
<!--                  </svg>-->
<!--               </span>-->
<!--            </a>-->
<!--            <div id="submenu-1" class="collapse submenu submenu-1" data-bs-parent="#menu-accordion">-->
<!--              <ul class="submenu-list list-unstyled">-->
<!--                <li class="submenu-item"><a class="submenu-link" href="notifications.html">Notifications</a></li>-->
<!--                <li class="submenu-item"><a class="submenu-link" href="account.html">Account</a></li>-->
<!--                <li class="submenu-item"><a class="submenu-link" href="settings.html">Settings</a></li>-->
<!--              </ul>-->
<!--            </div>-->
<!--          </li>-->
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/admin/login.html.erb
<!DOCTYPE html>
<html lang="en">
<body class="app app-login p-0">
<div class="row g-0 app-auth-wrapper">
  <div class="col-12 col-md-7 col-lg-6 auth-main-col d-flex justify-content-center align-items-center text-center p-5">
    <div class="">
      <div class="app-auth-body mx-auto">
        <div class="app-auth-branding mb-4"><a class="app-logo" href="<%= admin_login_path %>"><%= image_tag("admin-logo.png", alt: "MyShop Logo", style: "width: 280px;") %></a></div>
        <h2 class="auth-heading text-center mb-5">Log in to Admin Dashboard</h2>
        <div class="auth-form-container text-start">
          <%= form_for(@resource, as: @resource_name, url: session_path(@resource_name), class: 'auth-form login-form') do |f| %>
            <div class="email mb-3">
              <label class="sr-only" for="signin-email">Email</label>
              <%= f.email_field :email, class: "form-control signin-email", placeholder: "Name your email", autofocus: true  %>
            </div><!--//form-group-->
            <div class="password mb-3">
              <label class="sr-only" for="signin-password">Password</label>
              <%= f.password_field :password, class: "form-control signin-password", placeholder: "Choose a password" %>
            </div><!--//form-group-->
            <div class="text-center">
              <button type="submit" class="btn btn-success w-100 theme-btn mx-auto">Log In</button>
            </div>
          <%end %>
        </div><!--//auth-form-container-->
      </div><!--//auth-body-->

    </div><!--//flex-column-->
  </div><!--//auth-main-col-->
  <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
    <div class="auth-background-holder" style="background:url('<%= asset_path("background-3.jpg") %>')">
    </div>
    <div class="auth-background-mask"></div>
    <div class="auth-background-overlay p-3 p-lg-5">
      <div class="d-flex flex-column align-content-end h-100">
        <div class="h-100"></div>
        <div class="overlay-content p-3 p-lg-4 rounded">
          <h5 class="mb-3 overlay-title">MyShop.PK - Your Gateway To Quality Shopping</h5>
          <div>MyShop.PK is your premier destination for a seamless online shopping experience. As a leading e-commerce portal, we offer a diverse range of products, from electronics and fashion to home essentials, all curated to meet your modern lifestyle needs. With a user-friendly interface, secure payment options, and swift delivery services, we strive to make your shopping journey convenient and enjoyable. Explore the latest trends, discover exclusive deals, and indulge in the convenience of doorstep delivery with MyShop.PK – Your Gateway To Quality Shopping.</div>
        </div>
      </div>
    </div><!--//auth-background-overlay-->
  </div><!--//auth-background-col-->

</div><!--//row-->


</body>
</html>