config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "product#index"
  get '/product-detail/:product_name', to: 'product#productDetail', as: 'product_detail'

  get '/category/:category_name/products/', to: 'product#categoryProducts', as: 'category_products'

  # get '/login', to: 'users#user_login', as: 'login'
  # post "/login" => "users#check_credentials", as: :check_credentials
  # get "/logout" => "users#logout", as: :logout

  get '/about_us', to: 'home#about', as: 'about_us'
  get '/contact_us', to: 'home#contact', as: 'contact_us'

  get '/my-profile', to: 'users#profile', as: 'user_profile'
  get '/edit-profile', to: 'users#edit_profile', as: 'edit_profile'
  post '/update-profile/:id', to: 'users#update_profile', as: 'update_profile'


  get '/reset_password', to: 'users#new_password_reset', as: 'new_password_reset'
  post '/reset-password-action', to: 'users#create_password_reset', as: 'password_reset'
  get '/reset_password/:token/edit', to: 'users#edit_password_reset', as: :edit_password_reset
  patch '/reset_password/:token', to: 'users#update_password_reset', as: :reset_password


  get '/sign-up', to: 'users#sign_up_form', as: 'sign_up'
  post '/create-users', to: 'users#create_user', as: 'create_user'

  get '/cart', to: 'cart#index', as: 'my_cart'
  post '/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  get '/delete_cart/:id', to: 'cart#delete_cart', as: 'delete_cart'
  get '/checkout', to: 'cart#checkout', as: 'checkout'

  post '/place-an-order', to: 'order#place_order', as: 'place_an_order'

  namespace :admin do
    get '/', to: 'dashboard#login', as: 'login'
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    get 'users', to: 'dashboard#users', as: 'users'
    get 'orders', to: 'dashboard#orders', as: 'orders'
    get 'products', to: 'dashboard#products', as: 'products'
    get 'product/new', to: 'dashboard#new_product', as: 'add_product'
    post 'product/create', to: 'dashboard#create_product', as: 'create_product'
    get 'product/delete/:id', to: 'dashboard#delete_product', as: 'delete_product'
    get 'product/edit/:id', to: 'dashboard#edit_product', as: 'edit_product'
    get 'product/:id/remove-image', to: 'dashboard#remove_product_image', as: 'remove_product_image'
    patch 'product/update/:id', to: 'dashboard#update_product', as: 'update_product'

    resources :categories do
      member do
        get 'delete_category', to: 'categories#destroy_category', as: 'delete_category'
      end
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_ancestry
  has_one_attached :image

  validates :title, presence: true

  has_many :categorizations
  has_many :products, through: :categorizations
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  def index
    @categories = Category.includes(image_attachment: [:blob])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if(@category.ancestry == "")
      @category.ancestry = nil
    end
    if @category.save
      redirect_to admin_categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def destroy_category
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path, notice: 'Category was successfully deleted.'
  end

  def edit
    @category = Category.find(params[:id])
    @is_edit = true;
    render 'admin/categories/new'
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: 'Category was successfully updated.'
    else
      render 'edit_category'
    end
  end



  private

  def category_params
    params.require(:category).permit(:title, :ancestry, :image)
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/admin/categories/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body class="app">

<%= render 'admin/header' %>

<div class="app-wrapper">
  <div class="app-content pt-3 p-md-3 p-lg-4">
    <div class="container-xl">
      <h1 class="app-page-title">Categories</h1>
      <hr class="mb-4">
      <div class="row g-4 mb-4">
        <% flash.each do |type, message| %>
          <div class="alert <%= flash_class(type) %>">
            <%= message %>
          </div>
        <% end %>
      </div>

      <div class="row mb-4">
        <div class="col-auto">
          <div class="page-utilities">
            <div class="row g-2">
              <div class="col-auto">
                <a href="<%= new_admin_category_path %>" class="btn btn-success">Add Category</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="tab-content" id="orders-table-tab-content">
        <div class="row">
          <div class="col-12 col-md-12">
            <div class="app-card app-card-orders-table shadow-sm mb-5">
              <div class="app-card-body">
                <div class="table-responsive">
                  <table class="table app-table-hover mb-0 text-left">
                    <thead>
                    <tr>
                      <th class="cell">SR#</th>
                      <th class="cell">Image</th>
                      <th class="cell">Title</th>
                      <th class="cell">Parent</th>
                      <th class="cell">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @categories.each_with_index do |category, index| %>
                      <tr>
                        <td class="cell"><%= index + 1 %></td>
                        <td class="cell">
                          <%= image_tag category.image,  style:'width:70px;height:70px;' if category.image.attached? %>
                        </td>
                        <td class="cell"><%= category.title %></td>
                        <td class="cell">
                          <% if category.has_parent? %>
                            <%= category.parent.title %>
                          <% else %>

                          <% end %>
                        </td>
                        <td class="cell">
                          <%= link_to raw('<i class="fa fa-edit" style="margin-top:8px;"></i>'), edit_admin_category_path(category), method: :get, class: 'btn btn-sm btn-primary mt-4', title: 'Edit Product', style: 'width:40px;'%>
                          <%= link_to raw('<i class="fa fa-trash" style="margin-top:8px;"></i>'), delete_category_admin_category_path(category), method: :delete, data: { confirm: 'Are you sure you want to delete this category?' }, class: 'btn btn-sm btn-danger mt-4', title: 'Remove Product', style: 'width:40px;'%>
                        </td>
                      </tr>
                    <% end %>
                    </tbody>
                  </table>
                </div>

              </div>
            </div>
            <nav class="app-pagination">
              <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">Next</a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/admin/categories/new.html.erb
<!DOCTYPE html>
<html lang="en">
<body class="app">

<%= render 'admin/header' %>

<div class="app-wrapper">
  <div class="app-content pt-3 p-md-3 p-lg-4">
    <div class="container-xl">
      <h1 class="app-page-title"><%= @is_edit?'Edit':'Add' %> Category</h1>
      <hr class="mb-4">
      <div class="row g-4 mb-4">
        <% flash.each do |type, message| %>
          <div class="alert <%= flash_class(type) %>">
            <%= message %>
          </div>
        <% end %>
      </div>

      <div class="tab-content" id="orders-table-tab-content">
        <div class="row g-4 settings-section">
          <div class="col-12 col-md-12">
            <div class="app-card app-card-settings shadow-sm p-4">
              <div class="app-card-body">
                <%= form_with(model: @category, url: @is_edit ? admin_category_path(@category) : admin_categories_path, method: @is_edit ? :patch : :post, local: true, class: 'settings-form') do |form| %>
                  <div class="mb-3">
                    <label for="setting-input-1" class="form-label">Name</label>
                    <%= form.text_field :title, class: 'form-control', placeholder: 'Enter category name' %>
                  </div>
                  <div class="mb-3">
                    <label for="setting-input-1" class="form-label">Ancestry</label>
                    <%= form.collection_select :ancestry, Category.all, :id, :title, { include_blank: true }, class: 'form-control' %>
                  </div>

                  <div class="mb-3">
                    <label for="setting-input-3" class="form-label">Image</label>
                    <%= form.file_field :image, class: 'form-control' %>
                  </div>
                  <%= form.submit @is_edit?'Update Category':'Create Category', class: 'btn btn-success' %>
                <%end %>
              </div><!--//app-card-body-->
            </div><!--//app-card-->
          </div>
        </div><!--//row-->
      </div>
    </div>
  </div>
</div>

</body>
</html>