config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "product#index"
  get '/product-detail/:product_name', to: 'product#productDetail', as: 'product_detail'

  get '/category/:category_name/products/', to: 'product#categoryProducts', as: 'category_products'

  # get '/login', to: 'users#user_login', as: 'login'
  # post "/login" => "users#check_credentials", as: :check_credentials
  # get "/logout" => "users#logout", as: :logout

  get '/about_us', to: 'home#about', as: 'about_us'
  get '/contact_us', to: 'home#contact', as: 'contact_us'

  get '/my-profile', to: 'users#profile', as: 'user_profile'
  get '/edit-profile', to: 'users#edit_profile', as: 'edit_profile'
  post '/update-profile/:id', to: 'users#update_profile', as: 'update_profile'


  get '/reset_password', to: 'users#new_password_reset', as: 'new_password_reset'
  post '/reset-password-action', to: 'users#create_password_reset', as: 'password_reset'
  get '/reset_password/:token/edit', to: 'users#edit_password_reset', as: :edit_password_reset
  patch '/reset_password/:token', to: 'users#update_password_reset', as: :reset_password


  get '/sign-up', to: 'users#sign_up_form', as: 'sign_up'
  post '/create-users', to: 'users#create_user', as: 'create_user'

  get '/cart', to: 'cart#index', as: 'my_cart'
  post '/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  get '/delete_cart/:id', to: 'cart#delete_cart', as: 'delete_cart'
  get '/checkout', to: 'cart#checkout', as: 'checkout'

  post '/place-an-order', to: 'order#place_order', as: 'place_an_order'

  namespace :admin do
    get '/', to: 'dashboard#login', as: 'login'
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    get 'users', to: 'dashboard#users', as: 'users'
    get 'orders', to: 'dashboard#orders', as: 'orders'
    get 'products', to: 'dashboard#products', as: 'products'
    get 'product/new', to: 'dashboard#new_product', as: 'add_product'
    post 'product/create', to: 'dashboard#create_product', as: 'create_product'
    get 'product/delete/:id', to: 'dashboard#delete_product', as: 'delete_product'
    get 'product/edit/:id', to: 'dashboard#edit_product', as: 'edit_product'
    get 'product/:id/remove-image', to: 'dashboard#remove_product_image', as: 'remove_product_image'
    patch 'product/update/:id', to: 'dashboard#update_product', as: 'update_product'

    resources :categories do
      member do
        get 'delete_category', to: 'categories#destroy_category', as: 'delete_category'
      end
    end
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
  validates :p_name, presence: true
  validates :p_desc, presence: true
  validates :p_price, presence: true

  has_many :carts
  has_many :order_items
  has_one_attached :p_image, dependent: :destroy
  attr_accessor :image_url
  paginates_per 12


  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  def has_orders?
    order_items.any?
  end

  def has_carts?
    carts.any?
  end

  def self.check_product_use(product)
    if product.has_orders? || product.has_carts?
      return true, "You can't delete this product, it is already in use somewhere."
    else
      return false, nil
    end
  end


  def self.ransackable_attributes(auth_object = nil)
    %w[p_name]
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index


      puts "Ransack parameters: #{params[:q]}"
      @q = Product.includes(:categories, p_image_attachment: [:blob]).ransack(params[:q])
      @products_data = @q.result(distinct: true).page(params[:page])

      @serialized_products = @products_data.map do |product|
        product_url = "http://localhost:3000" + "#{rails_blob_path(product.p_image, only_path: true)}"
        product.define_singleton_method(:image_url) { product_url }
        product
      end

      @products = Rails.cache.fetch('products', expires_in: 1.hour) do
        @serialized_products
      end

      @categories = Rails.cache.fetch('categories', expires_in: 1.hour) do
        Category.includes(image_attachment: [:blob]).order(Arel.sql('RANDOM()')).limit(8)
      end

  end

  def categoryProducts
    @categories = Category.all
    if params[:category_ids].present?
      category_ids = params[:category_ids]
      @products = Product.includes(p_image_attachment: [:blob]).joins(:categories).where(categories: { id: category_ids }).distinct
    else
      @category = Category.find_by(title: params[:category_name])
      @products = @category.products.includes(p_image_attachment: [:blob]).page(params[:page])
    end
    @product_count = @products.count
    render 'product/category_products'
  end

  def productDetail
    @product = Product.find_by(p_name: params[:product_name])
    categories = @product.categories
    @related_products = Product.includes(p_image_attachment: [:blob]).joins(:categories).where(categories: { id: categories }).distinct
    render 'product/product_detail'
  end

end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/admin/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body class="app">

<%= render 'admin/header' %>

<div class="app-wrapper">
  <div class="app-content pt-3 p-md-3 p-lg-4">
    <div class="container-xl">
      <h1 class="app-page-title">Products</h1>
      <hr class="mb-4">
      <div class="row g-4 mb-4">
        <% flash.each do |type, message| %>
          <div class="alert <%= flash_class(type) %>">
            <%= message %>
          </div>
        <% end %>
      </div>
      <div class="row mb-4">
        <div class="col-auto">
          <div class="page-utilities">
            <div class="row g-2">
              <div class="col-auto">
                <a href="<%= admin_add_product_path %>" class="btn btn-success" style="width: 130px;">Add Product</a>
              </div>
            </div>
          </div>
        </div>
      </div>


      <div class="tab-content" id="orders-table-tab-content">
        <div class="app-card app-card-orders-table shadow-sm mb-5">
          <div class="app-card-body">
            <div class="table-responsive">
              <table class="table app-table-hover mb-0 text-left">
                <thead>
                <tr>
                  <th class="cell">SR#</th>
                  <th class="cell">Product</th>
                  <th class="cell">Description</th>
                  <th class="cell">Price</th>
                  <th class="cell">Action</th>
                </tr>
                </thead>
                <tbody>
                <% @products.each_with_index do |product, index| %>
                  <tr>
                    <td class="cell"><%= index + 1 %></td>
                    <td class="cell">
                      <div class="row g-3 align-items-center">
                        <div class="col-12 col-lg-auto text-center text-lg-start">
                          <%= image_tag product.p_image, class: 'profile-image', style: 'width:70px;height:70px;border-radius:50%;' if product.p_image.attached? %>
                        </div>
                        <div class="col-12 col-lg-auto text-center text-lg-start">
                          <h4 class="notification-title mb-1" style="font-size: 16px;"><%= product.p_name %></h4>
                          <ul class="notification-meta list-inline mb-0">
                            <%= product.categories.pluck(:title).join(' | ') %>
                          </ul>
                        </div>
                      </div>
                    </td>
                    <td class="cell"><%= product.p_desc %></td>
                    <td class="cell"><%= product.p_price %></td>
                    <td>
                      <%= link_to raw('<i class="fa fa-edit" style="margin-top:8px;"></i>'), admin_edit_product_path(product), method: :get, class: 'btn btn-sm btn-primary mt-4', title: 'Edit Product', style: 'width:40px;'%>
                      <%= link_to raw('<i class="fa fa-trash" style="margin-top:8px;"></i>'), admin_delete_product_path(product), method: :delete, class: 'btn btn-sm btn-danger mt-4', title: 'Remove Product', style: 'width:40px;'%>
                    </td>
                  </tr>
                <%end %>

                </tbody>
              </table>
            </div><!--//table-responsive-->

          </div><!--//app-card-body-->
        </div><!--//app-card-->
        <nav class="app-pagination">
          <ul class="pagination justify-content-center">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            <li class="page-item active"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#">Next</a>
            </li>
          </ul>
        </nav><!--//app-pagination-->
      </div><!--//tab-content-->



    </div><!--//container-fluid-->
  </div><!--//app-content-->



</div><!--//app-wrapper-->

</body>
</html>

app/views/admin/products/new.html.erb
<!DOCTYPE html>
<html lang="en">
<body class="app">

  <%= render 'admin/header' %>

  <div class="app-wrapper">

    <div class="app-content pt-3 p-md-3 p-lg-4">
      <div class="container-xl">
        <h1 class="app-page-title"><%= @is_edit?'Edit':'Add' %> Product</h1>
        <hr class="mb-4">
        <div class="row g-4 mb-4">
          <% flash.each do |type, message| %>
            <div class="alert <%= flash_class(type) %>">
              <%= message %>
            </div>
          <% end %>
          <% if @product.errors.any? %>
            <div class="alert-error py-3">
              <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
        <div class="row g-4 settings-section">
          <div class="col-12 col-md-12">
            <div class="app-card app-card-settings shadow-sm p-4">
              <div class="app-card-body">
                <%= form_with(model: @product, url: @is_edit ? admin_update_product_path(@product) : admin_create_product_path, method: @is_edit ? :patch : :post, local: true, class:'settings-form') do |form| %>
                  <div class="mb-3">
                    <label for="setting-input-1" class="form-label">Name</label>
                    <%= form.text_field :p_name, class: 'form-control', placeholder: 'Enter product name' %>
                  </div>
                  <div class="mb-3">
                    <label for="setting-input-2" class="form-label">Price</label>
                    <%= form.text_field :p_price, class: 'form-control', placeholder: 'Enter product price' %>
                  </div>
                  <div class="mb-3">
                    <label for="setting-input-3" class="form-label">Description</label>
                    <%= form.text_area :p_desc, class: 'form-control', placeholder: 'Enter product description' %>
                  </div>

                  <div class="mb-3">
                    <% Category.all.each do |category| %>
                      <div class="field">
                        <%= form.check_box :category_ids, { multiple: true }, category.id, nil %>
                        <%= form.label "category_ids_#{category.id}", category.title %>
                      </div>
                    <% end %>
                  </div>

                  <% if @is_edit && @product.p_image.attached? %>
                    <div class="mb-3">
                      <%= image_tag @product.p_image, class: 'product-image' if @product.p_image.attached? %><br>
                      <%= link_to 'Remove Image', admin_remove_product_image_path(@product), method: :delete, class: 'text-danger', data: { confirm: 'Are you sure?' } %>
                    </div>
                  <%end %>

                  <div class="mb-3">
                    <label for="setting-input-3" class="form-label">Image</label>
                    <%= form.file_field :p_image, class: 'form-control' %>
                  </div>
                  <%= form.submit @is_edit?'Update Product':'Create Product', class: 'btn btn-success', style: 'width: 152px;' %>
                <%end %>
              </div><!--//app-card-body-->
            </div><!--//app-card-->
          </div>
        </div><!--//row-->

      </div><!--//container-fluid-->
    </div><!--//app-content-->

  </div><!--//app-wrapper-->

</body>
</html>